name: SFTP Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install lftp
      run: sudo apt-get install lftp

    - name: Deploy via SFTP
      env:
        FTP_HOST: ${{ secrets.SFTP_HOST }}
        FTP_USER: ${{ secrets.SFTP_USER }}
        FTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
      run: |
        lftp -c "
        open -u $FTP_USER,$FTP_PASSWORD $FTP_HOST;
        mirror -R ./ /remote/path/
        "
